### ISSUE TITLE
Authentication breaks when accessing JSM issue without permission

### ISSUE THREAD

**Issue by mgsantos** [atlassian-labs/msteams-jira-server#32]
We conducted an experiment to test the behavior of user permissions on Jira Software (JSW) and Jira Service Management (JSM) projects on MS Teams. We found that when the user “vwong-sd-demo” was part of the “jira-software-users” group, we are able to edit the issue SCRUM1-10 in MS Teams.

However, when the same user was not a licensed JSM user, we were not able to edit the issue ITSM1-10 in Teams, which was the expected behavior (due to lack of permission), but we get in an infinite loop of Teams asking for authentication.
![image](https://user-images.githubusercontent.com/1018819/224070454-aa0ec27a-db74-4eea-b651-4a2040ae5281.png)

The following was confirmed by @vhensorskyi:
* If the user is not a member of jira-servicedesk-users an infinite loop of the login page or the unhandledRejection error appears. Depending on what role is assigned to the user. 
* if the user belongs to the group but doesn’t contain any role in the project the unhandledRejection error shows on the task module.
* if the user belongs to the group and either Service Desk Team or Administrator role is applied then user is able to edit issues in MS Teams.
![image](https://user-images.githubusercontent.com/1018819/224070313-6803afbf-d171-4fa3-87f6-252838d856b6.png)
![image](https://user-images.githubusercontent.com/1018819/224070360-0f13ab04-008a-47ca-b41f-88ce5346210e.png)
![image](https://user-images.githubusercontent.com/1018819/224070408-d1637780-d6d3-4c65-8732-40b9772d8ff4.png)

**Comment by vbatr** [comment]
Issue has been fixed and now permissions should be handled properly for Jira Service Management projects. 
If user do not have an access to the project and proper license we will show the next screen if user is trying to edit ticket
![Screenshot 2023-08-14 at 13 15 49](https://github.com/atlassian-labs/msteams-jira-server/assets/20244602/584b07bd-5bf5-401a-ac9b-ff46e92bb90e)

If user has an access to the project, but do not have JSM license  fields will be disabled:

![Screenshot 2023-08-14 at 13 16 45](https://github.com/atlassian-labs/msteams-jira-server/assets/20244602/3305176c-df8d-4b76-bc87-9be112791fd9)

If user has an access to the project and proper license:
![Screenshot 2023-08-14 at 13 16 13](https://github.com/atlassian-labs/msteams-jira-server/assets/20244602/437fdae4-e051-4be4-947a-0859ccbb4360)
