### ISSUE TITLE
Unable to unwatch issues with most recent versions of the App

### ISSUE THREAD

**Issue by pcora** [atlassian-labs/msteams-jira-server#6]
When trying to unwatch a ticket, MS Teams gets:

> Something went wrong in the Jira Server application

And in the application logs, we can see the following when the request to remove a watcher is received by Jira:

`2022-05-26 07:33:02,459+0100 OkHttp https://msteams-jira-server.service.signalr.net/... INFO      [c.m.teams.service.SignalRService] Message received: {"requestUrl":"api/2/issue/ISSUE-KEY/watchers?username=some.user.here","requestType":"DELETE","requestBody":"","token":"TRIMMED>...","teamsId":"<TRIMMED>","atlasId":"<TRIMMED>"}
`
And Jira's response is:
`2022-05-26 07:33:02,579+0100 OkHttp https://msteams-jira-server.service.signalr.net/... DEBUG      [c.m.teams.service.SignalRService] SignalR invoke hub method Callback() with response: {"code":415,"response":"","message":"Something went wrong in Jira Server application."}`

---

This does not happens with the latest version on Marketplace. But it's happening at least with the following:

* 2022.06.95
* 2022.02.88 - Provided to a customer with additional logging for debug purposes.

**Comment by vbatr** [comment]
fixed by https://github.com/atlassian-labs/msteams-jira-server-addon/issues/10
